services:
    app:
        container_name: isi-burger
        image: isi-burger:latest
        ports:
            - "8000:80"
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: postgresql
            DB_PORT: 5434
            DB_DATABASE: isiburger
            DB_USERNAME: linho
            DB_PASSWORD: linho
        depends_on:
            - postgresql
        networks:
            - isi-burger-network
        restart: unless-stopped
    postgresql:
        container_name: ms_pg_sql
        image: postgres
        environment:
            POSTGRES_USER: linho
            POSTGRES_PASSWORD: linho
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5434:5432"
        networks:
            - isi-burger-network
        restart: unless-stopped

    pgadmin:
        container_name: ms_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - isi-burger-network
        restart: unless-stopped

networks:
    isi-burger-network:
        driver: bridge

volumes:
    postgres:
    pgadmin:

